# When a new tag is created matching the pattern 'vN+.N+.N+',
# build a zip file with the content.

on:
    push:
        branches:
            master
        tags:
            - 'v[0-9][0-9]*\.[0-9][0-9]*\.[0-9].*'

name: Build release zip

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 3.1.101

            - name: Install dependencies
              run: dotnet restore

            - name: Build the binaries
              run: |
                  dotnet publish `
                    -p:PublishProfile=Properties/PublishProfiles/FolderProfile.pubxml `
                    --configuration=Release

            - name: Create release.zip
              id: release
              shell: pwsh
              working-directory: Publish
              run: |
                  Compress-Archive -Path * -DestinationPath ../release.zip
                  $fields = "${{ github.ref }}" -Split '/'
                  $tag = $fields[-1]
                  echo "::set-output name=tag::$tag"
            - name: Create github release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ steps.release.outputs.tag }}
                  draft: false
                  prerelease: false

            - name: Upload zip to release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: release.zip
                  asset_name: SFSEd.${{ steps.release.outputs.tag }}.zip
                  asset_content_type: application/zip

